#!/bin/sh
#
#
#__LINUX_INIT_INFO__
# chkconfig: 2345 99 01
# description: CA SSO WAMUI

### BEGIN INIT INFO
# Provides: smadminui
# Required-Start: $network $smpolicy
# Required-Stop:
# Default-Start: 2 3 5
# Default-Stop:  0 1 6
# Description: CA SSO WAMUI
### END INIT INFO

sleep 120

case "$1" in

'start')

su - srcpsusr -c /apps/CA/siteminder/adminui/bin/standalone.sh &

;;

'stop')

su - srcpsusr -c "/apps/CA/siteminder/adminui/bin/jboss-cli.sh -c --command=:shutdown"

;;

esac
